version: '3.9'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=sqs
    ports:
      - 4566:4566

  api-sqs:
    build: .
    container_name: api-sqs
    ports:
      - 8080:8080  
      
networks:
    default:
        name: sqs_network    
          